In [ ]:
import pandas as pd
data =pd.read_excel("/content/new excel.xlsx")

##Rename

In [ ]:
data = data.rename(columns={'Nights' : 'new night'})

In [ ]:
data.head(5)

,Booking_ID,Booking_Date,Room_Type,Customer_Type,new night,Room_Rate,Booking_Status
0,BKG00073,NaT,Standard,New,3,45.7,Completed
1,NaN,2025-12-27,Deluxe,New,10,69.03,Completed
2,BKG00016,2026-04-11,Deluxe,New,2,66.68,Confirmed
3,BKG00086,2025-08-30,Standard,Corporate,2,44.5,Completed
4,BKG00161,2025-08-18,Deluxe,NaN,10,78.87,Completed

##replace with values

In [ ]:
data ["Booking_Status"].value_counts()

Booking_Status
Completed    145
Confirmed     58
Cancelled     56
No-Show       22
-              1
Unknown        1
Name: count, dtype: int64

In [ ]:
data["Booking_Status"]=data ["Booking_Status"].replace({"completed" :"Completed" ,"confirmed" :"Confirmed"})

##Removing Unnecessary Colmuns

In [ ]:
data.drop(columns= "Nights"
)

##Changing Data Types

In [ ]:
data.dtypes

Booking_ID         object
Booking_Date      float64
Room_Type          object
Customer_Type      object
new night         float64
Room_Rate          object
Booking_Status     object
dtype: object

In [ ]:
##Using when data cleaning

data['new night']= pd.to_numeric(data['new night'].astype(float),errors="coerce")

In [ ]:

data['Booking_Date']=pd.to_numeric(data['Booking_Date'].astype(str),errors="coerce")