##import libararys

In [ ]:
#mport libarary pandas
#syntax for import (import library_items as pd)
import pandas as pd

# load dataset

In [ ]:
#read Data from Google Drive
data = pd.read_excel("/content/excel-hotel_analaysis.xlsx")

#Reading first 5 rows

In [ ]:
data.head()

#Read last 5 rows

In [ ]:
data.tail()

In [ ]:
data.sample(5)

,Booking_ID,Booking_Date,Room_Type,Customer_Type,Nights,Room_Rate,Booking_Status
279,BKG00079,2025-04-10,Standard,New,6,48.61,Completed
269,BKG00012,2026-04-08,Family,New,7,94.56,Cancelled
6,BKG00065,2025-04-26,Deluxe,New,2,72.98,Cancelled
79,BKG00262,2025-04-21,Suite,NaN,2,145,-
42,BKG00059,2025-07-29,Suite,Corporate,9,130.59,Completed

In [ ]:
data.shape

(302, 7)

## Display all colomn names of this dataset using property

In [ ]:
data.columns

Index(['Booking_ID', 'Booking_Date', 'Room_Type', 'Customer_Type', 'Nights',
       'Room_Rate', 'Booking_Status'],
      dtype='object')

Display the data tyoes of my dataset using property (datatype)

In [ ]:
data.dtypes

Booking_ID                object
Booking_Date      datetime64[ns]
Room_Type                 object
Customer_Type             object
Nights                    object
Room_Rate                 object
Booking_Status            object
dtype: object

##Genaral summary of data frame

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Booking_ID      286 non-null    object
 1   Booking_Date    283 non-null    datetime64[ns]
 2   Room_Type       283 non-null    object
 3   Customer_Type   284 non-null    object
 4   Nights          284 non-null    object
 5   Room_Rate       284 non-null    object
 6   Booking_Status  283 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 16.6+ KB

In [ ]:
data.describe(include="all")

,Booking_ID,Booking_Date,Room_Type,Customer_Type,Nights,Room_Rate,Booking_Status
count,286,283,283,284,284.0,284.00,283
unique,278,NaN,7,5,13.0,274.00,8
top,BKG00160,NaN,Standard,New,4.0,105.56,Completed
freq,2,NaN,127,123,39.0,3.00,143
mean,NaN,2025-10-15 07:17:35.830388736,NaN,NaN,NaN,NaN,NaN
min,NaN,2025-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN
25%,NaN,2025-05-08 12:00:00,NaN,NaN,NaN,NaN,NaN
50%,NaN,2025-10-15 00:00:00,NaN,NaN,NaN,NaN,NaN
75%,NaN,2026-03-04 12:00:00,NaN,NaN,NaN,NaN,NaN
max,NaN,2026-07-31 00:00:00,NaN,NaN,NaN,NaN,NaN